[[snippets]]
description = "Clear Chezmoi states"
command = "chezmoi state reset"
output = ""

[[snippets]]
description = "Clear Chezmoi state"
command = "chezmoi state delete --bucket=entryState --key=$HOME/.chezmoiscripts/02-app_defaults/preview.fish"
output = ""

[[snippets]]
description = "Clear plist state"
command = "defaults delete com.apple.Preview"
output = ""

[[snippets]]
description = "Update Chezmoi packages"
command = "chezmoi -v update"
output = ""

[[snippets]]
description = "Read plist state"
command = "defaults read com.apple.Preview"
output = ""

[[snippets]]
description = "Convert plist to xml"
command = "plutil -convert xml1 $HOME/Library/Preferences/$PLIST_NAME.plist -o $HOME/$PLIST_NAME.xml"
output = ""

[[snippets]]
description = "Sleep for six seconds"
command = "sleep 6"
output = ""

[[snippets]]
description = "Sleep for seven seconds"
command = "sleep 7"
output = ""