[core]
taps = ['homebrew/bundle',
        'homebrew/services', 
        'homebrew/cask-fonts']
brews = ['mas',
         'chezmoi',
         'fish',
         'fisher']
casks = ['1password']
vscodes = []

[ide]
taps = []
brews = []
casks = ["visual-studio-code"]
vscodes = ["PenumbraTheme.penumbra", 
           "GitHub.copilot", 
           "GitHub.copilot-chat", 
           "Willumz.generic-pseudocode", 
           "hediet.debug-visualizer", 
           "ms-vscode.hexeditor", 
           "EdwinHuiSH.better-comments-next"]


[cpp]
taps = []
brews = ["gcc", 
         "clang-format", 
         "catch2"]
casks = []         
vscodes = ["ms-vscode.cpptools", 
           "cschlosser.doxdocgen", 
           "jeff-hykin.better-cpp-syntax", 
           "Hyeon.c-math-viewer"]

[shell]
taps = []
brews = ["shfmt", # Autoformat shell script source code
         "shellcheck"] # Static analysis tool for shell scripts
casks = []         
vscodes = ["foxundermoon.shell-format", 
           "timonwong.shellcheck", 
           "bmalehorn.vscode-fish"]

[cs_225]
taps = []
brews = []
casks = ["docker"]
vscodes = ["ms-vscode-remote.remote-containers", 
           "ms-vscode-remote.remote-ssh", 
           "ms-vscode-remote.remote-ssh-edit", 
           "ms-vscode.remote-explorer"]

[cs_233]
taps = ["chipsalliance/verible",
        "randomplum/gtkwave"]
brews = ["icarus-verilog",
         "verible"]
casks = ["gtkwave"]
vscodes = ["AngaBlue.asm-formatter", 
           "kdarkhan.mips", 
           "teros-technology.teroshdl"] # Verilog Formatter and Syntax Highlight

[ruby]
taps = []
brews = ["rbenv", 
         "ruby-build", 
         "libyaml"]  
casks = []
vscodes = []         

[python]           
taps = []
brews = ["pyenv", 
         "xz"]
casks = []         
vscodes = ["ms-python.black-formatter", 
           "ms-python.python", 
           "ms-python.vscode-pylance", 
           "njpwerner.autodocstring"]
           # yt-dlp # youtube-dl fork with more features and less bugs

[manim]
taps = []
brews =  ["ffmpeg", 
          "pango", 
          "pkg-config"]
casks = ["mactex-no-gui"]
vscodes = ["Rickaym.manim-sideview"]
# pip install manim?
# pip install yt-dlp
# pip install pycairo
# pip install scipy

[utils]
taps = []
brews = ["cheat", 
         "tree", 
         "tldr", 
         "trash", #CLI tool that moves files or folder to the trash
         "ugrep", 
         "bat", 
         "bat-extras", 
         "eza",
         "d2"] # Diagramming tool
casks = []         
vscodes = ["terrastruct.d2"]

[apps]
taps = []
brews = []
casks = ["rectangle", # Window manager
         "breaktimer", # Pomodoro timer
         "alt-tab", # Better alt-tab
         "shottr", # Screenshot tool
         "obsidian", # Note taking
         "mullvad-browser", # Private Browser
         "mimestream", # Email client
         "discord", # Chat
         "arc", # Better Chrome
         "maccy", # Clipboard manager
         "iina", # Better VLC
         "adobe-acrobat-pro", #"adobe-acrobat-pro"
         "zoom", # Video conferencing
         "motrix", # Torrent client
         "cyberduck", # File transfer client
         "skype", # Video conferencing
         "anylist", # Grocery list
         "heynote", # Scratchpad for developers 
         "only-switch", # Hidden Menu Bar
         "github", # GitHub Desktop (Great for squashing Large # of Commits)
         ]
vscodes = []         







