[core]
taps = ['homebrew/bundle',
        'homebrew/services', 
        'homebrew/cask-fonts']
brews = ['mas',
         'chezmoi',
         'fish',
         'fisher']
casks = ['1password']

[utilities]
brews = ["cheat", 
         "tree", 
         "tldr", 
         "trash", 
         "ugrep", 
         "bat", 
         "bat-extras", 
         "eza"]

[ide]
casks = ["visual-studio-code"]
vscodes = ["PenumbraTheme.penumbra", 
           "GitHub.copilot", 
           "GitHub.copilot-chat", 
           "Willumz.generic-pseudocode", 
           "hediet.debug-visualizer", 
           "ms-vscode.hexeditor", 
           "EdwinHuiSH.better-comments-next"]



