[core]
taps = [
  "homebrew/bundle",
  "homebrew/services",
  "homebrew/cask-fonts"
]
brews = [
  "mas", 
  "chezmoi", 
  "fish", 
  "fisher" 
]
casks = ["1password"]
vscodes = [ ]

[ide]
taps = [ ]
brews = [ ]
casks = ["visual-studio-code" ]
vscodes = [
  "PenumbraTheme.penumbra",
  "GitHub.copilot",
  "GitHub.copilot-chat",
  "Willumz.generic-pseudocode",
  "hediet.debug-visualizer",
  "ms-vscode.hexeditor",
  "EdwinHuiSH.better-comments-next"
]

[utils]
taps = [ ]
brews = [
  "cheat",
  "tre-command",
  "trash",
  "ugrep",
  "bat",
  "bat-extras",
  "eza",
  "zoxide",
  "fzf",
  "d2"
]
casks = [ ]
vscodes = [ "terrastruct.d2" ]

[shell]
taps = [ ]
brews = [ 
  "shfmt", 
  "shellcheck"
]
casks = [ ]
vscodes = [
  "foxundermoon.shell-format",
  "timonwong.shellcheck",
  "bmalehorn.vscode-fish"
]

[apps]
taps = [ ]
brews = [ ]
casks = [ "github" ]
vscodes = [ ]
